const allSets = [
  'RNA Guild Kit',
  'Core Set 2020 Tokens',
  'M20 Promo Packs',
  'Core Set 2020 Promos',
  'Core Set 2020',
  'Signature Spellbook: Gideon',
  'Modern Horizons Promos',
  'Modern Horizons',
  'Modern Horizons Tokens',
  'War of the Spark Tokens',
  'Mythic Edition',
  'War of the Spark',
  'Magic Online Promos',
  'Judge Gift Cards 2019',
  'War of the Spark Promos',
  'RNA Ravnica Weekend',
  'RNA Guild Kit Tokens',
  'Ravnica Allegiance Promos',
  'Ravnica Allegiance Tokens',
  'Ravnica Allegiance',
  'Pro Tour Promos',
  'MagicFest 2019',
  'Planechase Anthology Planes',
  'Ultimate Box Topper',
  'Ultimate Masters',
  'Ultimate Masters Tokens',
  'Treasure Chest',
  'Happy Holidays',
  'Game Night',
  'M19 Gift Pack',
  'Vintage Championship',
  'Legacy Championship',
  'GRN Guild Kit Tokens',
  'GRN Guild Kit',
  'Guilds of Ravnica Tokens',
  'Guilds of Ravnica Promos',
  'GRN Ravnica Weekend',
  'Guilds of Ravnica',
  'Mythic Edition Tokens',
  'Commander 2018 Oversized',
  'Commander 2018 Tokens',
  'Commander 2018',
  '2017 Heroes of the Realm',
  'San Diego Comic-Con 2018',
  'Arena New Player Experience',
  'MTG Arena Promos',
  'Core Set 2019 Tokens',
  'M19 Standard Showdown',
  'Core Set 2019 Promos',
  'Core Set 2019',
  'Resale Promos',
  'Global Series Jiang Yanggu & Mu Yanling',
  'Signature Spellbook: Jace',
  'Grand Prix Promos',
  'Battlebond Promos',
  'Commander Anthology Volume II Tokens',
  'Battlebond Tokens',
  'Commander Anthology Volume II',
  'Battlebond',
  'Dominaria Tokens',
  'Dominaria',
  'Dominaria Promos',
  'Duel Decks: Elves vs. Inventors Tokens',
  'Duel Decks: Elves vs. Inventors',
  'Masters 25',
  'Masters 25 Tokens',
  '2018 Lunar New Year',
  'Nationals Promos',
  'Rivals of Ixalan Tokens',
  'Rivals of Ixalan Promos',
  'Rivals of Ixalan',
  'Judge Gift Cards 2018',
  'Friday Night Magic 2018',
  'Unstable',
  'Iconic Masters Tokens',
  'From the Vault: Transform',
  'XLN Treasure Chest',
  'Explorers of Ixalan',
  'Iconic Masters',
  'Unstable Tokens',
  'Unstable Promos',
  'Duel Decks: Merfolk vs. Goblins',
  'Duel Decks: Merfolk vs. Goblins Tokens',
  '2017 Gift Pack',
  'Ixalan',
  'Ixalan Tokens',
  'Ixalan Promos',
  'XLN Standard Showdown',
  'HasCon 2017',
  '2016 Heroes of the Realm',
  'World Magic Cup Qualifiers',
  'Archenemy: Nicol Bolas Tokens',
  'Commander 2017 Oversized',
  'Commander 2017 Tokens',
  'Commander 2017',
  'San Diego Comic-Con 2017',
  'Hour of Devastation',
  'Hour of Devastation Tokens',
  'Hour of Devastation Promos',
  'Archenemy: Nicol Bolas Schemes',
  'Archenemy: Nicol Bolas',
  'Commander Anthology Tokens',
  'Commander Anthology',
  'Amonkhet',
  'Amonkhet Promos',
  'Amonkhet Tokens',
  'Amonkhet Invocations',
  'Welcome Deck 2017',
  'Duel Decks: Mind vs. Might Tokens',
  'Duel Decks: Mind vs. Might',
  'Modern Masters 2017 Tokens',
  'Modern Masters 2017',
  'Aether Revolt Tokens',
  'Aether Revolt',
  'Aether Revolt Promos',
  'League Tokens 2017',
  'Judge Gift Cards 2017',
  'Friday Night Magic 2017',
  'Planechase Anthology Tokens',
  'Planechase Anthology',
  'Commander 2016 Oversized',
  'Commander 2016 Tokens',
  'Commander 2016',
  'San Diego Comic-Con 2016',
  'Kaladesh',
  'Kaladesh Tokens',
  'Kaladesh Promos',
  'Kaladesh Inventions',
  'Duel Decks: Nissa vs. Ob Nixilis',
  'Conspiracy: Take the Crown Tokens',
  'Conspiracy: Take the Crown',
  'From the Vault: Lore',
  'Eldritch Moon Tokens',
  'Eldritch Moon',
  'Eldritch Moon Promos',
  'Eternal Masters Tokens',
  'Eternal Masters',
  'Shadows over Innistrad Tokens',
  'Shadows over Innistrad',
  'Shadows over Innistrad Promos',
  'Welcome Deck 2016',
  'Duel Decks: Blessed vs. Cursed',
  'Oath of the Gatewatch Tokens',
  'Oath of the Gatewatch',
  'Oath of the Gatewatch Promos',
  'League Tokens 2016',
  'Judge Gift Cards 2016',
  'Friday Night Magic 2016',
  'Legendary Cube Prize Pack',
  'Commander 2015 Tokens',
  'Commander 2015 Oversized',
  'Commander 2015',
  'Battle for Zendikar Tokens',
  'Battle for Zendikar',
  'BFZ Standard Series',
  'Battle for Zendikar Promos',
  'Zendikar Expeditions',
  'Duel Decks: Zendikar vs. Eldrazi',
  'From the Vault: Angels',
  'Magic Origins Clash Pack',
  'Magic Origins Promos',
  'Magic Origins Tokens',
  'Magic Origins',
  'San Diego Comic-Con 2015',
  'Modern Masters 2015 Tokens',
  'Modern Masters 2015',
  'Tempest Remastered',
  'Tarkir Dragonfury',
  'Dragons of Tarkir Tokens',
  'Dragons of Tarkir',
  'Dragons of Tarkir Promos',
  'Duel Decks: Elspeth vs. Kiora',
  'URL/Convention Promos',
  'Fate Reforged Promos',
  'Fate Reforged Clash Pack',
  'Fate Reforged Tokens',
  'Fate Reforged',
  'Ugin\'s Fate',
  'League Tokens 2015',
  'Judge Gift Cards 2015',
  'Friday Night Magic 2015',
  'Duel Decks Anthology: Jace vs. Chandra Tokens',
  'Duel Decks Anthology: Divine vs. Demonic Tokens',
  'Duel Decks Anthology: Garruk vs. Liliana Tokens',
  'Duel Decks Anthology: Elves vs. Goblins Tokens',
  'Duel Decks Anthology: Jace vs. Chandra',
  'Duel Decks Anthology: Garruk vs. Liliana',
  'Duel Decks Anthology: Elves vs. Goblins',
  'Duel Decks Anthology: Divine vs. Demonic',
  'Celebration Cards',
  'Commander 2014 Oversized',
  'Commander 2014 Tokens',
  'Commander 2014',
  'Khans of Tarkir Tokens',
  'Khans of Tarkir',
  'Khans of Tarkir Promos',
  'Duel Decks: Speed vs. Cunning',
  'From the Vault: Annihilation',
  'Magic 2015 Tokens',
  'Magic 2015',
  'Magic 2015 Clash Pack',
  'Magic 2015 Promos',
  'M15 Prerelease Challenge',
  'San Diego Comic-Con 2014',
  'Vintage Masters',
  'Launch Parties',
  'Conspiracy Tokens',
  'Conspiracy',
  'Modern Event Deck 2014 Tokens',
  'Modern Event Deck 2014',
  'Defeat a God',
  'Journey into Nyx Tokens',
  'Journey into Nyx Hero\'s Path',
  'Journey into Nyx',
  'Journey into Nyx Promos',
  'Duel Decks: Jace vs. Vraska Tokens',
  'Duel Decks: Jace vs. Vraska',
  'Battle the Horde',
  'Born of the Gods Hero\'s Path',
  'Born of the Gods Tokens',
  'Born of the Gods',
  'Born of the Gods Promos',
  'Duels of the Planeswalkers Promos 2014',
  'IDW Comics 2014',
  'League Tokens 2014',
  'Judge Gift Cards 2014',
  'Friday Night Magic 2014',
  'Commander 2013 Oversized',
  'Commander 2013',
  'Face the Hydra',
  'Theros Tokens',
  'Theros',
  'Theros Hero\'s Path',
  'Theros Promos',
  'Duel Decks: Heroes vs. Monsters Tokens',
  'Duel Decks: Heroes vs. Monsters',
  'From the Vault: Twenty',
  'Magic 2014 Tokens',
  'Magic 2014',
  'Magic 2014 Promos',
  'San Diego Comic-Con 2013',
  'Modern Masters Tokens',
  'Modern Masters',
  'Dragon\'s Maze',
  'Dragon\'s Maze Tokens',
  'Dragon\'s Maze Promos',
  'Duel Decks: Sorin vs. Tibalt Tokens',
  'Duel Decks: Sorin vs. Tibalt',
  'Gatecrash',
  'Gatecrash Tokens',
  'Gatecrash Promos',
  'Duels of the Planeswalkers Promos 2013',
  'IDW Comics 2013',
  'League Tokens 2013',
  'Judge Gift Cards 2013',
  'Friday Night Magic 2013',
  'Commander\'s Arsenal Oversized',
  'Commander\'s Arsenal',
  'Return to Ravnica',
  'Return to Ravnica Promos',
  'Return to Ravnica Tokens',
  'Duel Decks: Izzet vs. Golgari Tokens',
  'Duel Decks: Izzet vs. Golgari',
  'From the Vault: Realms',
  'Magic 2013 Tokens',
  'Magic 2013',
  'Magic 2013 Promos',
  'Planechase 2012 Planes',
  'Promotional Planes',
  'Planechase 2012',
  'Avacyn Restored Tokens',
  'Avacyn Restored',
  'Open the Helvault',
  'Avacyn Restored Promos',
  'Duel Decks: Venser vs. Koth Tokens',
  'Duel Decks: Venser vs. Koth',
  'Dark Ascension Tokens',
  'Dark Ascension',
  'Dark Ascension Promos',
  'IDW Comics 2012',
  'Wizards Play Network 2012',
  'Duels of the Planeswalkers Promos 2012',
  'League Tokens 2012',
  'Judge Gift Cards 2012',
  'Friday Night Magic 2012',
  'Premium Deck Series: Graveborn',
  'Innistrad Tokens',
  'Innistrad',
  'Innistrad Promos',
  'Duel Decks: Ajani vs. Nicol Bolas Tokens',
  'Duel Decks: Ajani vs. Nicol Bolas',
  'From the Vault: Legends',
  'Magic 2012 Tokens',
  'Magic 2012',
  'Magic 2012 Promos',
  'Commander 2011 Oversized',
  'Commander 2011 Launch Party',
  'Commander 2011',
  'Duel Decks: Mirrodin Pure vs. New Phyrexia',
  'New Phyrexia Tokens',
  'New Phyrexia',
  'New Phyrexia Promos',
  'Duel Decks: Knights vs. Dragons Tokens',
  'Duel Decks: Knights vs. Dragons',
  'Mirrodin Besieged Tokens',
  'Mirrodin Besieged',
  'Mirrodin Besieged Promos',
  'Masters Edition IV',
  'Duels of the Planeswalkers Promos 2011',
  'Wizards Play Network 2011',
  'Magic Player Rewards 2011',
  'Judge Gift Cards 2011',
  'Friday Night Magic 2011',
  'Premium Deck Series: Fire and Lightning',
  'Magic Online Theme Decks',
  'Scars of Mirrodin Tokens',
  'Scars of Mirrodin',
  'Scars of Mirrodin Promos',
  'Duel Decks: Elspeth vs. Tezzeret Tokens',
  'Duel Decks: Elspeth vs. Tezzeret',
  'From the Vault: Relics',
  'Magic 2011 Tokens',
  'Magic 2011',
  'Magic 2011 Promos',
  'Archenemy Schemes',
  'Archenemy',
  'Promotional Schemes',
  'Duels of the Planeswalkers',
  'Rise of the Eldrazi Promos',
  'Rise of the Eldrazi Tokens',
  'Rise of the Eldrazi',
  'Duel Decks: Phyrexia vs. the Coalition Tokens',
  'Duel Decks: Phyrexia vs. the Coalition',
  'Worldwake Promos',
  'Worldwake',
  'Worldwake Tokens',
  'Duels of the Planeswalkers Promos 2010',
  'Wizards Play Network 2010',
  'Magic Player Rewards 2010',
  'Judge Gift Cards 2010',
  'Friday Night Magic 2010',
  'Premium Deck Series: Slivers',
  'Duel Decks: Garruk vs. Liliana Tokens',
  'Duel Decks: Garruk vs. Liliana',
  'Zendikar Promos',
  'Zendikar',
  'Zendikar Tokens',
  'Masters Edition III',
  'Planechase Planes',
  'Planechase',
  'From the Vault: Exiled',
  'Magic 2010 Tokens',
  'Magic 2010',
  'Magic 2010 Promos',
  'Alara Reborn Tokens',
  'Alara Reborn',
  'Prerelease Events',
  'Duel Decks: Divine vs. Demonic Tokens',
  'Duel Decks: Divine vs. Demonic',
  'Conflux Tokens',
  'Conflux',
  'Miscellaneous Book Promos',
  'Wizards Play Network 2009',
  'Duels of the Planeswalkers Promos 2009',
  'Magic Player Rewards 2009',
  'Judge Gift Cards 2009',
  'Friday Night Magic 2009',
  'Duel Decks: Jace vs. Chandra Tokens',
  'Duel Decks: Jace vs. Chandra',
  'Shards of Alara Tokens',
  'Shards of Alara',
  'Wizards Play Network 2008',
  'Masters Edition II',
  'From the Vault: Dragons',
  'Eventide Tokens',
  'Eventide',
  'Shadowmoor Tokens',
  'Shadowmoor',
  '15th Anniversary Cards',
  'Champs and States',
  'Morningtide Tokens',
  'Morningtide',
  'Junior Super Series',
  'Junior Series Europe',
  'Junior APAC Series',
  'Gateway 2008',
  'Magic Player Rewards 2008',
  'Judge Gift Cards 2008',
  'Friday Night Magic 2008',
  'Duel Decks: Elves vs. Goblins Tokens',
  'Duel Decks: Elves vs. Goblins',
  'Release Events',
  'Lorwyn Tokens',
  'Lorwyn',
  'Masters Edition',
  'Summer of Magic',
  'Tenth Edition',
  'Tenth Edition Promos',
  'Tenth Edition Tokens',
  'Future Sight',
  'Planar Chaos',
  'Gateway 2007',
  'Magic Player Rewards 2007',
  'Judge Gift Cards 2007',
  'Friday Night Magic 2007',
  'Time Spiral',
  'Time Spiral Timeshifted',
  'Coldsnap Tokens',
  'Coldsnap Theme Decks',
  'Coldsnap',
  'Dissension',
  'Guildpact',
  'Arena League 2006',
  'Hachette UK',
  'Gateway 2006',
  'Magic Player Rewards 2006',
  'Judge Gift Cards 2006',
  'Friday Night Magic 2006',
  'Two-Headed Giant Tournament',
  'Ravnica: City of Guilds',
  'Ninth Edition',
  'Saviors of Kamigawa',
  'Betrayers of Kamigawa',
  'Arena League 2005',
  'Magic Player Rewards 2005',
  'Judge Gift Cards 2005',
  'Friday Night Magic 2005',
  'Unhinged',
  'Champions of Kamigawa',
  'World Championship Decks 2004',
  'Fifth Dawn',
  'Darksteel',
  'Arena League 2004',
  'Magic Player Rewards 2004',
  'Judge Gift Cards 2004',
  'Friday Night Magic 2004',
  'Mirrodin',
  'World Championship Decks 2003',
  'Eighth Edition',
  'Scourge',
  'Legions',
  'Magic Online Avatars',
  'Arena League 2003',
  'Magic Player Rewards 2003',
  'Judge Gift Cards 2003',
  'Friday Night Magic 2003',
  'Onslaught',
  'World Championship Decks 2002',
  'Judgment',
  'Torment',
  'Arena League 2002',
  'Magic Player Rewards 2002',
  'Judge Gift Cards 2002',
  'Friday Night Magic 2002',
  'Deckmasters',
  'Odyssey',
  'World Championship Decks 2001',
  'Apocalypse',
  'Seventh Edition',
  'Planeshift',
  'Magazine Inserts',
  'Arena League 2001',
  'Magic Player Rewards 2001',
  'Judge Gift Cards 2001',
  'Friday Night Magic 2001',
  'Invasion',
  'Beatdown Box Set',
  'World Championship Decks 2000',
  'Prophecy',
  'Starter 2000',
  'Nemesis',
  'European Land Program',
  'Arena League 2000',
  'Judge Gift Cards 2000',
  'Friday Night Magic 2000',
  'Battle Royale Box Set',
  'Mercadian Masques',
  'Wizards of the Coast Online Store',
  'World Championship Decks 1999',
  'Worlds',
  'Guru',
  'Starter 1999',
  'Urza\'s Destiny',
  'Portal Three Kingdoms',
  'Classic Sixth Edition',
  'Urza\'s Legacy',
  'Arena League 1999',
  'Judge Gift Cards 1999',
  'Anthologies',
  'Urza\'s Saga',
  'Asia Pacific Land Program',
  'World Championship Decks 1998',
  'Unglued Tokens',
  'Unglued',
  'Exodus',
  'Portal Second Age',
  'Stronghold',
  'Judge Gift Cards 1998',
  'Tempest',
  'World Championship Decks 1997',
  'Weatherlight',
  'Vanguard Series',
  'Portal Demo Game',
  'Portal',
  'Fifth Edition',
  'Visions',
  'Introductory Two-Player Set',
  'Multiverse Gift Box',
  'Mirage',
  'Arena League 1996',
  'Rivals Quick Start Set',
  'Alliances',
  'Pro Tour Collector Set',
  'Homelands',
  'Chronicles',
  'Ice Age',
  'HarperPrism Book Promos',
  'Fourth Edition',
  'DCI Legend Membership',
  'Fallen Empires',
  'The Dark',
  'Dragon Con',
  'Summer Magic / Edgar',
  'Legends',
  'Revised Edition',
  'Antiquities',
  'Arabian Nights',
  'Intl. Collectors’ Edition',
  'Collectors’ Edition',
  'Unlimited Edition',
  'Limited Edition Beta',
  'Limited Edition Alpha'];

